import {
    Dna,
    Folder,
    Palette,
    FileText,
    Trash2,
    RefreshCw,
    Wand2,
    Image as ImageIcon,
    Settings,
    X,
    Plus,
    ChevronRight,
    ChevronDown,
    ChevronUp,
    Maximize,
    Minimize2,
    ZoomIn,
    ZoomOut,
    Save,
    Play,
    Pause,
    Sparkles,
    RotateCw,
    RotateCcw,
    Share2,
    Square,
    Eye,
    EyeOff,
    Activity,
    Wind,
    Zap,
    Layers,
    Move,
    Music,
    Waves,
    Anchor,
    Copy,
    Check,
    Search,
    Crop,
    MousePointer,
    Clapperboard,
    ArrowRight,
    LogIn,
    Keyboard,
} from 'lucide-react';

const icons = {
    app: Sparkles,
    sprites: Dna,
    scene: Clapperboard,
    scenes: Folder,
    generate: Sparkles,
    logs: FileText,
    save: Save,
    delete: Trash2,
    play: Play,
    pause: Pause,
    revert: RefreshCw,
    optimize: Wand2,
    image: ImageIcon,
    config: Settings,
    settings: Settings,
    close: X,
    add: Plus,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    maximize: Maximize,
    zoomIn: ZoomIn,
    zoomOut: ZoomOut,
    rotateCw: RotateCw,
    rotateCcw: RotateCcw,
    share: Share2,
    stop: Square,
    visible: Eye,
    hidden: EyeOff,
    oscillate: Waves,
    drift: Wind,
    pulse: Zap,
    background: Layers,
    location: Anchor,
    sound: Music,
    copy: Copy,
    check: Check,
    expand: ChevronDown,
    collapse: ChevronUp,
    minimize: Minimize2,
    search: Search,
    crop: Crop,
    pointer: MousePointer,
    rotate: RotateCw,
    login: LogIn,
    arrowRight: ArrowRight,
    sortUp: ChevronUp,
    sortDown: ChevronDown,
    keyboard: Keyboard,
};

const VARIANTS = {
    tight: 16,
    roomy: 32
};

export const Icon = ({ name, size, variant = 'tight', className, ...props }) => {
    const LucideIcon = icons[name] || icons.image;
    // Prefer explicit size if provided (backwards compat), otherwise use variant
    const finalSize = size || VARIANTS[variant] || VARIANTS.tight;
    return <LucideIcon size={finalSize} className={className} {...props} />;
};

